Obsidian = Obsidian or {};
if (not Obsidian.Localization) then
	Obsidian.Localization = {};
	Obsidian.Localization.Language = {};
end

Obsidian.Localization.Language[SystemData.Settings.Language.ENGLISH] = 
{
	["Setup.Menu.Title"] = L"Obsidian",
	["Setup.Menu.Castbar"] = L"Castbar",
	["Setup.Menu.EffectTracker"] = L"Effect Tracker",
	
	["Strings.Alpha"] = L"Alpha",
	["Strings.Font"] = L"Font",
	["Strings.Color"] = L"Color",
	["Strings.Color.Red"] = L"Red",
	["Strings.Color.Green"] = L"Green",
	["Strings.Color.Blue"] = L"Blue",
	["Strings.Scale"] = L"Scale",
	["Strings.Texture"] = L"Texture",
	["Strings.Offset"] = L"Offset",
	["Strings.Offset.X"] = L"X",
	["Strings.Offset.Y"] = L"Y",
	["Strings.Size"] = L"Size",
	["Strings.Size.Width"] = L"Width",
	["Strings.Size.Height"] = L"Height",
	["Strings.Position"] = L"Position",
	["Strings.Position.Left"] = L"Left",
	["Strings.Position.Right"] = L"Right",
	["Strings.Position.Top"] = L"Top",
	["Strings.Position.Bottom"] = L"Bottom",
	["Strings.Position.Free"] = L"Free",
	["Strings.Example"] = L"Example",
	["Strings.Align"] = L"Align",
	["Strings.Align.Left"] = L"Left",
	["Strings.Align.Center"] = L"Center",
	["Strings.Align.Right"] = L"Right",
	
	["Setup.Castbar.Title"] = L"Castbar",
	["Setup.Castbar.Element"] = L"Element",
	["Setup.Castbar.General"] = L"General",
	["Setup.Castbar.General.Accurate"] = L"Accuracy",
	["Setup.Castbar.General.Accurate.Enable"] = L"Hide the castbar when casting is finished without waiting for the server",
	["Setup.Castbar.Background"] = L"Background",
	["Setup.Castbar.Background.Border"] = L"Border",
	["Setup.Castbar.Fill"] = L"Fill",
	["Setup.Castbar.FillReady"] = L"Fill (Ready)",
	["Setup.Castbar.Divider"] = L"Divider",
	["Setup.Castbar.Fill.Colors"] = L"Colors",
	["Setup.Castbar.Fill.Colors.Normal"] = L"Normal",
	["Setup.Castbar.Fill.Colors.Channeled"] = L"Channel",
	["Setup.Castbar.Fill.Colors.Success"] = L"Success",
	["Setup.Castbar.Fill.Colors.Failed"] = L"Failed",
	["Setup.Castbar.Fill.UpdatePriority"] = L"Update priority",
	["Setup.Castbar.Fill.UpdatePriority.Low"] = L"Low",
	["Setup.Castbar.Fill.UpdatePriority.Normal"] = L"Normal",
	["Setup.Castbar.Fill.UpdatePriority.High"] = L"High",
	["Setup.Castbar.Latency"] = L"Latency",
	["Setup.Castbar.Latency.Info"] = L"Latency is calculated when a spell is interrupted by jumping",
	["Setup.Castbar.Latency.Enable"] = L"Show latency bar",
	["Setup.Castbar.Latency.Text.Enable"] = L"Show latency text",
	["Setup.Castbar.Spark"] = L"Spark",
	["Setup.Castbar.Name"] = L"Spell name",
	["Setup.Castbar.Timer"] = L"Spell timer",
	["Setup.Castbar.Timer.Decimals"] = L"Decimals",
	["Setup.Castbar.Icon"] = L"Spell icon",
	["Setup.Castbar.Icon.Enable"] = L"Show spell icon",
	["Setup.Castbar.GlobalCooldown"] = L"Global cooldown",
	["Setup.Castbar.GlobalCooldown.Enable"] = L"Show global cooldown bar",
	["Setup.Castbar.GlobalCooldown.Reverse"] = L"Reverse fill direction",
	["Setup.Castbar.GlobalCooldown.Elements"] = L"Elements",
	["Setup.Castbar.Range"] = L"Range",
	["Setup.Castbar.Range.Enable"] = L"Enable out of range (or line of sight) coloring",
	
	["Setup.EffectTracker.Title"] = L"Effect Tracker",
	["Setup.EffectTracker.Bars"] = L"Bars",
	["Setup.EffectTracker.Bars.Spacing"] = L"Spacing between bars",
	["Setup.EffectTracker.Bars.MaximumDuration"] = L"Maximum duration threshold",
	["Setup.EffectTracker.Bars.FixedDuration"] = L"Fix bars to a specified duration",
	["Setup.EffectTracker.Bars.Duration.Seconds"] = L"seconds",
	["Setup.EffectTracker.Friendly"] = L"Friendly Target",
	["Setup.EffectTracker.Friendly.Enable"] = L"Enable friendly target effects",
	["Setup.EffectTracker.Tracker.Position"] = L"Position",
	["Setup.EffectTracker.Tracker.Position.TopLeft"] = L"Top Left",
	["Setup.EffectTracker.Tracker.Position.TopRight"] = L"Top Right",
	["Setup.EffectTracker.Tracker.Position.BottomLeft"] = L"Bottom Left",
	["Setup.EffectTracker.Tracker.Position.BottomRight"] = L"Bottom Right",
	["Setup.EffectTracker.Tracker.Position.FreeUp"] = L"Free (Grow up)",
	["Setup.EffectTracker.Tracker.Position.FreeDown"] = L"Free (Grow down)",
	["Setup.EffectTracker.Tracker.FillColor"] = L"Color fill by",
	["Setup.EffectTracker.Tracker.FillColor.BuffDebuff"] = L"Buff/Debuff",
	["Setup.EffectTracker.Tracker.FillColor.EffectType"] = L"Effect Type",
	["Setup.EffectTracker.Tracker.FillColor.Custom"] = L"Custom",
	["Setup.EffectTracker.Tracker.MaximumEffects"] = L"Maximum effects to display",
	["Setup.EffectTracker.Hostile"] = L"Hostile Target",
	["Setup.EffectTracker.Hostile.Enable"] = L"Enable hostile target effects",
};

